repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: check-json
  - id: check-xml
  - id: debug-statements
  - id: check-symlinks
  - id: debug-statements

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.3
  hooks:
  - id: ruff-check
    args: [ --fix, --exit-non-zero-on-fix ]
  - id: ruff-format

- repo: https://github.com/rhysd/actionlint
  rev: v1.7.7
  hooks:
  - id: actionlint-docker
    args:
    - -ignore
    - 'SC2155:'
    - -ignore
    - 'SC2086:'
    - -ignore
    - 'SC1004:'
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.33.0
  hooks:
  - id: check-github-actions
- repo: https://github.com/python-poetry/poetry
  rev: '2.1.3'
  hooks:
  - id: poetry-check
  - id: poetry-install
ci:
  skip:
  - actionlint-docker
  - check-github-actions
  - poetry-install
